server:
  port: 8091

spring:
  application:
    name: seata-server

seata:
  server:
    http:
      filter:
        xss:
          enabled: true
    enable-degrade: false
    service:
      enable-degrade: false
      disable-global-transaction: false
    config:
      type: file
    registry:
      type: file

logging:
  level:
    seata: debug